Repository Cyber4All/clark-client, pull requests merged in 2018-09, with the labels that each got.

#374 Reimplement organization link to details page header
  package-lock.json
  package.json
  src/app/cube/details/splash/details-splash.component.html
Labels: bite size

#402 Update whitelist.json
  whitelist/whitelist.json
Labels: WIP

#423 Recently Released
  package-lock.json
  package.json
  src/app/cube/browse/browse.component.ts
  src/app/cube/home/featured/featured.component.ts
  src/app/cube/home/featured/featured.copy.ts
  src/app/cube/home/home.component.html
  src/app/cube/home/home.component.ts
  src/app/cube/learning-object.service.ts
  src/app/onion/dashboard/dashboard.component.html
  src/app/shared/interfaces/query.ts
Labels: WIP

#428 Fix collection filter doesn't select from URL
  package-lock.json
  package.json
  src/app/cube/browse/browse.component.ts
  src/app/shared/interfaces/query.ts
Labels: bug
