Repository Cyber4All/clark-client, pull requests merged in 2018-10, with the labels that each got.

#429 Fix showing contributors when there aren't any
  package-lock.json
  package.json
  src/app/cube/details/splash/details-splash.component.html
Labels: bug

#438 Fix no standard outcome sources
  package-lock.json
  package.json
  src/app/core/outcome.service.ts
Labels: bug

#465 Add Academic Levels to Details Page
  package-lock.json
  package.json
  src/app/cube/details/details.component.html
  src/app/cube/details/details.component.scss
Labels: feature request

#433 Implement file previews for office, open office, and pdfs
  package-lock.json
  package.json
  src/app/cube/details/details.component.ts
  src/app/onion/content-upload/app/upload/upload.component.ts
  src/app/shared/filesystem/file-list-view/file-list-view.component.html
  src/app/shared/filesystem/file-list-view/file-list-view.component.scss
  src/app/shared/filesystem/file-list-view/file-list-view.component.ts
  src/environments/route.ts
Labels: WIP
