Repository Cyber4All/clark-client, pull requests merged in 2019-03, with the labels that each got.

#690 Fix files not appearing on details page when navigating to a Learning Object that has files with the same path
  package-lock.json
  package.json
  src/app/shared/filesystem/DirectoryTree.ts
  src/app/shared/filesystem/file-browser/file-browser.component.ts
Labels: review

#688 Implement routing changes to allow for different admin/curator views
  src/app/admin/admin.component.html
  src/app/admin/admin.component.ts
  src/app/admin/admin.routing.ts
  src/app/admin/components/sidebar/sidebar.component.html
  src/app/admin/components/sidebar/sidebar.component.ts
  src/app/admin/pages/learning-objects/learning-objects.component.html
  src/app/core/auth.service.ts
Labels: review

#684 Search for Learning Objects in the Curator Dashboard (Unit 2 of 2)
  package-lock.json
  package.json
  src/app/admin/admin.module.ts
  src/app/admin/components/search-bar/search-bar.component.html
  src/app/admin/components/search-bar/search-bar.component.ts
  src/app/admin/pages/learning-objects/learning-objects.component.html
  src/app/admin/pages/learning-objects/learning-objects.component.scss
  src/app/admin/pages/learning-objects/learning-objects.component.ts
  src/app/clark.module.ts
  src/app/clark.routing.ts
  src/app/core/access-group-guard.ts
  src/app/core/auth.service.ts
  src/app/core/core.module.ts
  src/app/cube/details/action-panel/action-panel.component.html
  src/app/cube/details/action-panel/action-panel.component.ts
  src/app/onion/core/learning-object.service.ts
  src/app/onion/dashboard/dashboard.component.ts
  src/app/onion/learning-object-builder/builder-store.service.ts
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.html
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.scss
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.ts
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.html
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.ts
  src/app/onion/learning-object-builder/learning-object-builder.component.html
  src/app/onion/learning-object-builder/learning-object-builder.component.ts
  src/app/shared/dashboard-item/dashboard-item.component.html
  src/app/shared/dashboard-item/dashboard-item.component.ts
  src/app/shared/filesystem/DirectoryTree.ts
  src/app/shared/filesystem/file-browser/file-browser.component.ts
Labels: review

#694 Refactor builder-store
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/builder-store.service.ts
Labels: review

#695 Implement builder-store service error handling
  src/app/onion/learning-object-builder/builder-store.service.ts
Labels: review

#692 Implement user search in the Curator Dashboard
  src/app/admin/admin.component.ts
  src/app/admin/admin.module.ts
  src/app/admin/components/search-bar/search-bar.component.scss
  src/app/admin/components/sidebar/sidebar.component.ts
  src/app/admin/components/user-card/user-card.component.html
  src/app/admin/components/user-card/user-card.component.scss
  src/app/admin/components/user-card/user-card.component.spec.ts
  src/app/admin/components/user-card/user-card.component.ts
  src/app/admin/pages/learning-objects/learning-objects.component.scss
  src/app/admin/pages/users/users.component.html
  src/app/admin/pages/users/users.component.scss
  src/app/admin/pages/users/users.component.ts
Labels: review

#689 Allow Editors and Admins to Change Learning Object Status from the Builder
  package-lock.json
  package.json
  src/_vars.scss
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.html
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.scss
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.html
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.scss
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.spec.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.component.html
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.component.scss
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.component.spec.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.component.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.module.ts
  src/app/onion/learning-object-builder/learning-object-builder.module.ts
  src/app/onion/onion.module.ts
  src/app/onion/shared/onion-shared.module.ts
  src/app/onion/shared/status-indicator/status-indicator.component.scss
  src/app/onion/shared/status-indicator/status-indicator.component.ts
Labels: feature request, review

#697 User card context menu in Collection Dashboard
  src/_vars.scss
  src/app/admin/admin.routing.ts
  src/app/admin/components/user-card/user-card.component.html
  src/app/admin/components/user-card/user-card.component.scss
  src/app/admin/components/user-card/user-card.component.ts
  src/app/admin/pages/learning-objects/learning-objects.component.ts
  src/app/admin/pages/users/users.component.html
  src/app/admin/pages/users/users.component.scss
  src/app/admin/pages/users/users.component.ts
Labels: review

#701 Implement homepage redesign
  src/app/cube/core/usage-stats/usage-stats.service.ts
  src/app/cube/home/_home.scss
  src/app/cube/home/components/about/about.component.html
  src/app/cube/home/components/about/about.component.scss
  src/app/cube/home/components/about/about.component.spec.ts
  src/app/cube/home/components/about/about.component.ts
  src/app/cube/home/components/collections/collections.component.html
  src/app/cube/home/components/collections/collections.component.scss
  src/app/cube/home/components/collections/collections.component.spec.ts
  src/app/cube/home/components/collections/collections.component.ts
  src/app/cube/home/components/philosophy/philosophy.component.html
  src/app/cube/home/components/philosophy/philosophy.component.scss
  src/app/cube/home/components/philosophy/philosophy.component.ts
  src/app/cube/home/components/splash/splash.component.html
  src/app/cube/home/components/splash/splash.component.scss
  src/app/cube/home/components/splash/splash.component.spec.ts
  src/app/cube/home/components/splash/splash.component.ts
  src/app/cube/home/components/usage/usage.component.html
  src/app/cube/home/components/usage/usage.component.scss
  src/app/cube/home/components/usage/usage.component.spec.ts
  src/app/cube/home/components/usage/usage.component.ts
  src/app/cube/home/home.component.html
  src/app/cube/home/home.component.scss
  src/app/cube/home/home.component.ts
  src/app/cube/home/home.copy.ts
  src/app/cube/home/home.module.ts
  src/app/cube/home/philosophy/philosophy.component.scss
  src/app/cube/home/stat-counters/stat-counters.component.html
  src/app/cube/home/stat-counters/stat-counters.component.scss
  src/app/cube/home/stat-counters/stat-counters.component.ts
  src/app/cube/shared/featured/featured.component.html
  src/app/cube/shared/featured/featured.component.scss
  src/app/cube/shared/footer/footer.component.scss
  src/app/cube/shared/types/index.ts
  src/app/cube/shared/types/learning-object-stats.ts
  src/app/cube/shared/types/usage-stats.ts
  src/app/cube/shared/types/user-stats.ts
  src/app/cube/usage-stats/usage-stats.component.ts
  src/app/shared/learning-object/learning-object.component.scss
  src/assets/fontawesome-5.3.1.min.js
  src/assets/fontawesome-5.7.2.min.js
  src/assets/images/lecturer.jpg
  src/index.html
Labels: review

#713 Hotfix/object card right click
  package-lock.json
  package.json
  src/app/shared/learning-object/learning-object.component.html
  src/app/shared/learning-object/learning-object.component.scss
  src/app/shared/new-rating/new-rating.component.ts
Labels: review

#714 Reimplement ability to view all learning objects from homepage
  src/app/cube/home/home.component.html
  src/app/cube/home/home.component.scss
Labels: review

#716 Merge staging branch into master
  src/app/cube/core/usage-stats/usage-stats.service.ts
  src/app/cube/home/_home.scss
  src/app/cube/home/components/about/about.component.html
  src/app/cube/home/components/about/about.component.scss
  src/app/cube/home/components/about/about.component.spec.ts
  src/app/cube/home/components/about/about.component.ts
  src/app/cube/home/components/collections/collections.component.html
  src/app/cube/home/components/collections/collections.component.scss
  src/app/cube/home/components/collections/collections.component.spec.ts
  src/app/cube/home/components/collections/collections.component.ts
  src/app/cube/home/components/philosophy/philosophy.component.html
  src/app/cube/home/components/philosophy/philosophy.component.scss
  src/app/cube/home/components/philosophy/philosophy.component.ts
  src/app/cube/home/components/splash/splash.component.html
  src/app/cube/home/components/splash/splash.component.scss
  src/app/cube/home/components/splash/splash.component.spec.ts
  src/app/cube/home/components/splash/splash.component.ts
  src/app/cube/home/components/usage/usage.component.html
  src/app/cube/home/components/usage/usage.component.scss
  src/app/cube/home/components/usage/usage.component.spec.ts
  src/app/cube/home/components/usage/usage.component.ts
  src/app/cube/home/home.component.html
  src/app/cube/home/home.component.scss
  src/app/cube/home/home.component.ts
  src/app/cube/home/home.copy.ts
  src/app/cube/home/home.module.ts
  src/app/cube/home/philosophy/philosophy.component.scss
  src/app/cube/home/stat-counters/stat-counters.component.html
  src/app/cube/home/stat-counters/stat-counters.component.scss
  src/app/cube/home/stat-counters/stat-counters.component.ts
  src/app/cube/shared/featured/featured.component.html
  src/app/cube/shared/featured/featured.component.scss
  src/app/cube/shared/footer/footer.component.scss
  src/app/cube/shared/types/index.ts
  src/app/cube/shared/types/learning-object-stats.ts
  src/app/cube/shared/types/usage-stats.ts
  src/app/cube/shared/types/user-stats.ts
  src/app/cube/usage-stats/usage-stats.component.ts
  src/app/shared/learning-object/learning-object.component.scss
  src/assets/fontawesome-5.3.1.min.js
  src/assets/fontawesome-5.7.2.min.js
  src/assets/images/lecturer.jpg
  src/index.html
Labels: review

#717 Hotfix for homepage gradient and collection-copy typo
  package-lock.json
  package.json
  src/app/cube/home/home.component.scss
  src/app/cube/home/home.copy.ts
Labels: review

#718 Adjust max-width on philosophy container to allow all items to sit on one row
  package-lock.json
  package.json
  src/app/cube/home/components/philosophy/philosophy.component.scss
Labels: review

#719 :bug: Fix wrong rating appearing for Learning Oject by resetting when…
  package-lock.json
  package.json
  src/app/cube/details/details.component.ts
Labels: review

#696 Complete builder error handling
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/builder-store.service.ts
  src/app/onion/learning-object-builder/learning-object-builder.component.html
  src/app/onion/learning-object-builder/learning-object-builder.component.scss
  src/app/onion/learning-object-builder/learning-object-builder.component.ts
Labels: review

#638 Add child reorder
  package-lock.json
  package.json
  src/app/onion/core/learning-object.service.ts
  src/app/onion/learning-object-builder/builder-store.service.ts
  src/app/onion/learning-object-builder/components/scaffold/hierarchy/hierarchy.component.html
  src/app/onion/learning-object-builder/components/scaffold/hierarchy/hierarchy.component.scss
  src/app/onion/learning-object-builder/components/scaffold/hierarchy/hierarchy.component.spec.ts
  src/app/onion/learning-object-builder/components/scaffold/hierarchy/hierarchy.component.ts
  src/app/onion/learning-object-builder/components/scaffold/scaffold.component.html
  src/app/onion/learning-object-builder/components/scaffold/scaffold.component.scss
  src/app/onion/learning-object-builder/components/scaffold/scaffold.component.ts
  src/app/onion/learning-object-builder/learning-object-builder.module.ts
  src/app/onion/learning-object-builder/pages/info-page/info-page.component.html
  src/app/onion/learning-object-builder/pages/materials-page/materials-page.component.html
  src/app/onion/learning-object-builder/pages/materials-page/materials-page.component.ts
  src/app/onion/learning-object-builder/pages/outcome-page/outcome-page.component.html
  src/app/onion/learning-object-builder/pages/outcome-page/outcome-page.component.ts
  src/environments/route.ts
Labels: review

#722 Fix bug where opening the builder before the children route has resolved causes angular template errors
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/components/scaffold/scaffold.component.html
Labels: review

#699 Feature/curator lo filter
  package-lock.json
  package.json
  src/app/admin/admin.module.ts
  src/app/admin/components/filter-search/filter-search.component.html
  src/app/admin/components/filter-search/filter-search.component.scss
  src/app/admin/components/filter-search/filter-search.component.ts
  src/app/admin/pages/learning-objects/learning-objects.component.html
  src/app/admin/pages/learning-objects/learning-objects.component.ts
  src/app/onion/learning-object-builder/builder-store.service.ts
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.html
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.scss
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.html
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.scss
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.spec.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.component.html
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.component.scss
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.component.spec.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.component.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.module.ts
  src/app/onion/learning-object-builder/learning-object-builder.module.ts
  src/app/onion/onion.module.ts
  src/app/onion/shared/onion-shared.module.ts
  src/app/onion/shared/status-indicator/status-indicator.component.scss
  src/app/onion/shared/status-indicator/status-indicator.component.ts
  src/app/shared/shared.module.ts
Labels: review

#724 Fix broken links
  package-lock.json
  package.json
  src/app/cube/details/details.component.ts
  src/app/cube/details/included-in/parent-listing.component.ts
Labels: review

#700 Update single file upload route
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/builder-store.service.ts
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.ts
  src/app/onion/learning-object-builder/components/content-upload/environments/environment.prod.ts
  src/app/onion/learning-object-builder/components/content-upload/environments/environment.ts
  src/environments/route.ts
Labels: review

#735 Update link to point to cc 4.0
  package.json
  src/app/shared/popups/templates/collection-selector/collection-selector.component.html
Labels: review

#744 Navigate to dashboard if accessed builder via url
  package.json
  src/app/onion/learning-object-builder/learning-object-builder.component.ts
Labels: review

#725 Check for width and truncate collection
  package.json
  src/app/shared/learning-object/learning-object.component.html
  src/app/shared/learning-object/learning-object.component.ts
Labels: bite size, bug, review

#738 Feature/changelogs
  angular.json
  package-lock.json
  package.json
  src/app/core/changelog.service.ts
  src/app/core/core.module.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.html
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.scss
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/clark-change-status-modal.animations.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/edit-changelog/edit-changelog.component.html
  src/app/onion/learning-object-builder/components/editor-action-panel/edit-changelog/edit-changelog.component.scss
  src/app/onion/learning-object-builder/components/editor-action-panel/edit-changelog/edit-changelog.component.spec.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/edit-changelog/edit-changelog.component.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.module.ts
  src/app/onion/learning-object-builder/learning-object-builder.module.ts
  src/app/shared/shared.module.ts
  src/app/shared/text-editor.component.ts
  src/environments/route.ts
Labels: review

#747 Remove NSA logo from footer, replace nccp logo with new logo and remove secure coding community logo
  package.json
  src/app/cube/shared/footer/footer.component.html
  src/assets/images/collections/nccp.png
  src/assets/images/collections/secure_coding_community.png
Labels: review

#748 Filter unreleased parents
  package.json
  src/app/cube/details/included-in/included-in.service.ts
Labels: bug, review

#743 Add sentence to error message
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/builder-store.service.ts
Labels: review

#755 Feature/remove bullets
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/components/outcome/outcome-typeahead/outcome-typeahead.component.ts
Labels: bite size, review

#745 Wrap filter in a white box with shadow
  package-lock.json
  package.json
  src/app/cube/browse/browse.component.scss
Labels: review

#758 Add Terms of Service to Footer
  package-lock.json
  package.json
  src/app/cube/shared/footer/footer.component.html
  src/app/cube/shared/footer/footer.copy.ts
  src/assets/Terms.pdf
Labels: review

#756 Wrap scaffold in scroll wrapper
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/components/column-wrapper/column-wrapper.component.html
  src/app/onion/learning-object-builder/components/column-wrapper/column-wrapper.component.scss
Labels: review

#765 Improve browse page performance
  package-lock.json
  package.json
  src/app/cube/browse/browse.component.html
  src/app/cube/browse/browse.component.ts
  src/app/cube/cube.component.html
  src/app/cube/cube.component.scss
  src/app/cube/cube.module.ts
  src/app/cube/cube.routing.ts
  src/app/cube/shared/breadcrumb/breadcrumb.component.scss
  src/app/cube/shared/breadcrumb/breadcrumb.component.ts
  src/app/cube/shared/breadcrumb/router.component.ts
  src/app/cube/shared/cube-shared.module.ts
  src/app/shared/learning-object/learning-object.component.ts
Labels: review
