Repository Cyber4All/clark-client, pull requests merged in 2019-07, with the labels that each got.

#872 Add NSA logo to footer
  package-lock.json
  package.json
  src/app/cube/shared/footer/footer.component.html
  src/app/cube/shared/footer/footer.component.scss
Labels: review

#858 Configure Lighthouse in CI
  .circleci/config.yml
  Dockerfile
  Dockerfile-cypress
  cypress.json
  cypress/fixtures/creds.json
  cypress/fixtures/names.json
  cypress/fixtures/objects.json
  cypress/fixtures/register.json
  cypress/fixtures/route.json
  cypress/integration/Collection Dashboard/admin-privileges.spec.js
  cypress/integration/browse.spec.js
  cypress/integration/builder.spec.js
  cypress/integration/collection_dashboard.spec.js
  cypress/integration/dashboard.spec.js
  cypress/integration/details.spec.js
  cypress/integration/home.spec.js
  cypress/integration/library.spec.js
  cypress/integration/new_rating.spec.js
  cypress/integration/register.spec.js
  cypress/integration/user.spec.js
  cypress/plugins/index.js
  cypress/screenshots/builder.spec.js/Browse -- Successfully navigate to the manage materials page (step 3) (failed).png
  cypress/support/commands.js
  cypress/support/index.js
  lighthouse/jest.config.lighthouse.js
  lighthouse/jest.test.lighthouse.js
  package-lock.json
  package.json
  src/app/admin/pages/learning-objects/learning-objects.component.ts
Labels: review

#883 Lower performance threshold to 90%
  lighthouse/jest.test.lighthouse.js
  package.json
Labels: review

#884 View Changelogs from Details Page
  package.json
  src/app/core/changelog.service.ts
  src/app/cube/details/details.component.html
  src/app/cube/details/details.component.ts
  src/app/cube/details/splash/details-splash.component.html
  src/app/cube/details/splash/details-splash.component.scss
  src/app/cube/details/splash/details-splash.component.ts
  src/app/onion/onion.module.ts
  src/app/shared/changelog-item/changelog-item.component.html
  src/app/shared/changelog-item/changelog-item.component.scss
  src/app/shared/changelog-item/changelog-item.component.spec.ts
  src/app/shared/changelog-item/changelog-item.component.ts
  src/app/shared/changelog-list/changelog-list.component.html
  src/app/shared/changelog-list/changelog-list.component.scss
  src/app/shared/changelog-list/changelog-list.component.spec.ts
  src/app/shared/changelog-list/changelog-list.component.ts
  src/app/shared/changelog-modal/changelog-modal.component.html
  src/app/shared/changelog-modal/changelog-modal.component.scss
  src/app/shared/changelog-modal/changelog-modal.component.spec.ts
  src/app/shared/changelog-modal/changelog-modal.component.ts
  src/app/shared/identification-pill/identification-pill.component.html
  src/app/shared/identification-pill/identification-pill.component.scss
  src/app/shared/identification-pill/identification-pill.component.spec.ts
  src/app/shared/identification-pill/identification-pill.component.ts
  src/app/shared/shared.module.ts
  src/environments/route.ts
Labels: review

#892 Ignore build-and-test workflow when merging into master
  .circleci/config.yml
  package.json
Labels: review

#899 Fix Status Filter on Admin Dashboard is Not Filtering
  package.json
  src/app/admin/components/filter-search/filter-search.component.html
Labels: bug

#900 Revision sidebar on details page occasionally doesn't appear
  package.json
  src/app/core/auth.service.ts
  src/app/cube/details/details.component.html
  src/app/cube/details/details.component.ts
Labels: review

#886 Revision Interaction Stubs
  package.json
  src/app/onion/dashboard/components/side-panel-content/learning-object/learning-object.component.html
  src/app/onion/dashboard/components/side-panel-content/learning-object/learning-object.component.scss
  src/app/onion/dashboard/components/side-panel-content/learning-object/learning-object.component.spec.ts
  src/app/onion/dashboard/components/side-panel-content/learning-object/learning-object.component.ts
  src/app/onion/dashboard/components/side-panel-content/metrics/metrics.component.html
  src/app/onion/dashboard/components/side-panel-content/metrics/metrics.component.scss
  src/app/onion/dashboard/components/side-panel-content/metrics/metrics.component.spec.ts
  src/app/onion/dashboard/components/side-panel-content/metrics/metrics.component.ts
  src/app/onion/dashboard/components/side-panel-content/revision/revision.component.html
  src/app/onion/dashboard/components/side-panel-content/revision/revision.component.scss
  src/app/onion/dashboard/components/side-panel-content/revision/revision.component.spec.ts
  src/app/onion/dashboard/components/side-panel-content/revision/revision.component.ts
  src/app/onion/dashboard/components/side-panel-content/side-panel-content.component.html
  src/app/onion/dashboard/components/side-panel-content/side-panel-content.component.scss
  src/app/onion/dashboard/components/side-panel-content/side-panel-content.component.spec.ts
  src/app/onion/dashboard/components/side-panel-content/side-panel-content.component.ts
  src/app/onion/dashboard/components/side-panel-content/side-panel-content.module.ts
  src/app/onion/old-dashboard/components/side-panel-content/side-panel-content.component.html
  src/app/onion/old-dashboard/components/side-panel/side-panel-viewer/side-panel-viewer.component.scss
  src/app/onion/old-dashboard/old-dashboard.component.ts
  src/app/onion/onion.module.ts
Labels: WIP
