Repository Cyber4All/clark-client, pull requests merged in 2019-01, with the labels that each got.

#519 Use Access Groups instead of the Whitelist
  package-lock.json
  package.json
  src/app/core/auth.service.ts
  src/app/cube/browse/browse.component.ts
  src/app/cube/cart/cart.component.html
  src/app/cube/cart/cart.component.ts
  src/app/cube/home/home.component.ts
  src/app/onion/content-upload/app/upload/upload.component.ts
  src/app/onion/content-upload/environments/environment.prod.ts
  src/app/onion/content-upload/environments/environment.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  whitelist/whitelist.json
Labels: WIP, in progress

#535 Fix review pending banner not showing
  package-lock.json
  package.json
  src/app/cube/details/action-panel/action-panel.component.html
  src/app/cube/details/action-panel/action-panel.component.scss
  src/app/cube/details/action-panel/action-panel.component.ts
Labels: bug, review

#536 Hotfix/review pending
  package-lock.json
  package.json
  src/app/cube/details/action-panel/action-panel.component.ts
Labels: review

#527 Created Edit Button on Action Panel
  package-lock.json
  package.json
  src/app/core/auth.service.spec.ts
  src/app/core/auth.service.ts
  src/app/cube/browse/browse.component.ts
  src/app/cube/cart/cart.component.ts
  src/app/cube/details/action-panel/action-panel.component.html
  src/app/cube/details/action-panel/action-panel.component.ts
  src/app/cube/home/home.component.ts
  src/app/onion/content-upload/app/upload/upload.component.ts
  src/app/shared/contextmenu/context-menu-viewer/context-menu-viewer.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: review

#541 Replace C.L.A.R.K. with CLARK
  package-lock.json
  package.json
  src/app/cube/home/home.copy.ts
Labels: review

#542 Add comma to fix sentence grammar
  package-lock.json
  package.json
  src/app/shared/popups/templates/download-notice/download-notice.component.html
Labels: review

#537 Extend Home Page usage stats and create full usage stats page
  angular.json
  package-lock.json
  package.json
  src/app/cube/core/cube-core.module.ts
  src/app/cube/core/usage-stats/usage-stats.service.ts
  src/app/cube/cube.routing.ts
  src/app/cube/home/home.component.html
  src/app/cube/home/home.component.scss
  src/app/cube/home/home.component.ts
  src/app/cube/home/home.module.ts
  src/app/cube/home/stat-counters/stat-counters.component.html
  src/app/cube/home/stat-counters/stat-counters.component.scss
  src/app/cube/home/stat-counters/stat-counters.component.ts
  src/app/cube/shared/cube-shared.module.ts
  src/app/cube/shared/types/index.ts
  src/app/cube/shared/types/learning-object-stats.ts
  src/app/cube/shared/types/usage-stats.ts
  src/app/cube/shared/types/user-stats.ts
  src/app/cube/usage-stats/counter-block/counter-block.component.html
  src/app/cube/usage-stats/counter-block/counter-block.component.scss
  src/app/cube/usage-stats/counter-block/counter-block.component.ts
  src/app/cube/usage-stats/distribution-chart/distribution-chart.component.html
  src/app/cube/usage-stats/distribution-chart/distribution-chart.component.scss
  src/app/cube/usage-stats/distribution-chart/distribution-chart.component.ts
  src/app/cube/usage-stats/heat-map/heat-map.component.html
  src/app/cube/usage-stats/heat-map/heat-map.component.scss
  src/app/cube/usage-stats/heat-map/heat-map.component.ts
  src/app/cube/usage-stats/types/chart.ts
  src/app/cube/usage-stats/types/index.ts
  src/app/cube/usage-stats/usage-stats.component.html
  src/app/cube/usage-stats/usage-stats.component.scss
  src/app/cube/usage-stats/usage-stats.component.ts
  src/app/cube/usage-stats/usage-stats.module.ts
  src/app/cube/usage-stats/usage-stats.router.ts
  src/environments/route.ts
Labels: review

#543 Delete load spinner
  package.json
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.html
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.ts
  src/app/onion/learning-object-builder/pages/materials-page/materials-page.component.ts
Labels: review

#548 Add number pipe to homepage statistics to print numbers with appropriate commas
  package-lock.json
  package.json
  src/app/cube/home/stat-counters/stat-counters.component.html
  src/app/cube/usage-stats/counter-block/counter-block.component.html
  src/app/cube/usage-stats/usage-stats.component.ts
Labels: review

#555 Changed stats link in footer to redirect to new clark stats page
  package.json
  src/app/cube/shared/footer/footer.component.html
Labels: review

#540 Fix revise button showing after logout
  package.json
  src/app/cube/details/action-panel/action-panel.component.ts
Labels: bug, review

#557 Fix bug where creating a new outcome doesn't auto selected 'Remember and Understand'
  package.json
  src/app/onion/learning-object-builder/components/outcome-page/outcome/outcome.component.ts
Labels: review

#554 Change site title
  package-lock.json
  package.json
  src/index.html
Labels: review

#553 Modified makeQuery to check for filter values and update filters
  package.json
  src/app/cube/browse/browse.component.ts
Labels: review

#560 Removed span tag and put click function call on button instead of text
  package.json
  src/app/cube/details/action-panel/action-panel.component.html
Labels: review

#561 Added element in the philosophy component
  package.json
  src/app/cube/home/philosophy/philosophy.component.scss
  src/app/cube/home/philosophy/philosophy.component.ts
Labels: review

#566 Updated downloaded to downloads
  package-lock.json
  package.json
  src/app/cube/home/stat-counters/stat-counters.component.html
  src/app/cube/usage-stats/usage-stats.component.ts
Labels: review

#567 Change max width to 1250 and edited grid layout
  package.json
  src/app/cube/home/philosophy/philosophy.component.scss
Labels: review

#570 :camera_flash: add TU website link to TU logo
  package-lock.json
  package.json
  src/app/cube/shared/footer/footer.component.html
Labels: review

#574 Remove/collection filter
  package.json
  src/app/cube/browse/browse.component.ts
Labels: review

#575 Add tooltip to top bar in learning object pages
  package-lock.json
  package.json
  src/app/cube/details/splash/details-splash.component.html
  src/app/cube/details/splash/details-splash.component.scss
Labels: review

#576 Compress clouds.jpg
  package-lock.json
  package.json
  src/assets/images/clouds.jpg
Labels: review

#580 Fix bug where description doesn't save until second keystroke
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/components/text-editor.component.ts
Labels: review

#584 Fix deploy root directory
  .circleci/config.yml
  package-lock.json
  package.json
Labels: review

#586 Redesign collection selector to use a grid layout and refresh UI
  package-lock.json
  package.json
  src/app/onion/dashboard/dashboard.component.html
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.html
  src/app/shared/popups/popup-viewer/popup-viewer.component.scss
  src/app/shared/popups/templates/collection-selector/collection-selector.component.html
  src/app/shared/popups/templates/collection-selector/collection-selector.component.scss
  src/app/shared/popups/templates/collection-selector/collection-selector.component.ts
  src/globals.scss
Labels: review

#589 :bug: Fix broken file listing and folder structure issue
  package-lock.json
  package.json
  src/app/shared/filesystem/DirectoryTree.ts
  src/app/shared/filesystem/file-list-view/file-size.pipe.ts
Labels: review
