Repository Cyber4All/clark-client, pull requests merged in 2019-02, with the labels that each got.

#593 Update to Angular 7
  package-lock.json
  package.json
  src/app/auth/can-reset-password.guard.ts
  src/app/auth/register/recaptcha/recaptcha-validator.service.ts
  src/app/core/auth.service.ts
  src/app/core/collection.service.ts
  src/app/core/user.service.ts
  src/app/cube/browse/browse.component.ts
  src/app/cube/cart/cart.component.ts
  src/app/cube/core/profile.guard.ts
  src/app/cube/core/user.resolver.ts
  src/app/cube/details/action-panel/action-panel.component.ts
  src/app/cube/details/details.component.ts
  src/app/cube/details/file-details/file-details.component.ts
  src/app/cube/details/included-in/included-in.service.ts
  src/app/cube/learning-object.service.ts
  src/app/cube/shared/breadcrumb/breadcrumb.component.ts
  src/app/cube/shared/footer/footer.component.ts
  src/app/cube/user-profile/user-edit-information/user-edit-information.component.ts
  src/app/cube/user-profile/user-profile.component.ts
  src/app/onion/core/learning-object.service.ts
  src/app/onion/core/suggestion.service.ts
  src/app/onion/dashboard/dashboard.component.ts
  src/app/onion/learning-object-builder/components/content-upload/app/file-manager/file-manager.component.ts
  src/app/onion/learning-object-builder/components/content-upload/app/services/file-storage.service.ts
  src/app/onion/learning-object-builder/components/content-upload/app/upload/file-upload-status/file-upload-status.component.ts
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.ts
  src/app/onion/learning-object-builder/components/content-upload/app/upload/url-manager/url-manager.component.ts
  src/app/onion/learning-object-builder/components/outcome/outcome-typeahead/outcome-typeahead.component.ts
  src/app/onion/learning-object-builder/learning-object-builder.component.ts
  src/app/onion/learning-object-builder/pages/info-page/info-page.component.ts
  src/app/onion/learning-object-builder/pages/materials-page/materials-page.component.ts
  src/app/onion/learning-object-builder/pages/outcome-page/outcome-page.component.ts
  src/app/onion/mocks/learning-object.service.mock.ts
  src/app/shared/contextmenu/context-menu/context-menu.component.ts
  src/app/shared/contextmenu/contextmenu.service.ts
  src/app/shared/filesystem/file-breadcrumb/file-breadcrumb.component.ts
  src/app/shared/filesystem/file-browser/file-browser.component.ts
  src/app/shared/filesystem/file-list-view/file-list-view.component.ts
  src/app/shared/learning-object/learning-object.component.ts
  src/app/shared/mappings-filter/mappings-filter.component.ts
  src/app/shared/modals/modal.service.ts
  src/app/shared/navbar/navbar.component.ts
  src/app/shared/popups/popup-viewer/popup-viewer.component.scss
  src/app/shared/popups/popup.component.ts
  src/app/shared/search/search.component.ts
  src/main.ts
  src/polyfills.ts
  tsconfig.json
Labels: review

#592 Adjust modal spacing to allow for smaller and zoomed screens
  package-lock.json
  package.json
Labels: review

#595 Reimplement full-screen upload overlay in builder
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.html
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.scss
  src/app/shared/shared.module.ts
  src/app/shared/teleporter/teleporter-destination/teleporter-destination.component.html
  src/app/shared/teleporter/teleporter-destination/teleporter-destination.component.scss
  src/app/shared/teleporter/teleporter-destination/teleporter-destination.component.spec.ts
  src/app/shared/teleporter/teleporter-destination/teleporter-destination.component.ts
  src/app/shared/teleporter/teleporter.component.html
  src/app/shared/teleporter/teleporter.component.scss
  src/app/shared/teleporter/teleporter.component.spec.ts
  src/app/shared/teleporter/teleporter.component.ts
  src/app/shared/teleporter/teleporter.module.ts
Labels: review

#599 Implement minor refactor of the action panel for the details component
  package-lock.json
  package.json
  src/app/cube/details/action-panel/action-panel.component.ts
Labels: review

#598 Force page reload on logout
  package-lock.json
  package.json
  src/app/core/auth.service.ts
Labels: review

#596 Remove s from outcomes if there is only one outcome
  package-lock.json
  package.json
  src/app/cube/details/outcomes-detail-view/outcomes-detail-view.component.ts
Labels: review

#601 Adjust transition and animation properties in upload component
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.scss
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.ts
Labels: review

#602 Fix Status Error
  package-lock.json
  package.json
  src/app/core/messages.service.ts
  src/app/shared/navbar/message/message.component.ts
  src/environments/route.ts
Labels: bug, review

#609 Add proofing
  package-lock.json
  package.json
  src/app/onion/dashboard/dashboard-item/dashboard-item.component.html
  src/app/onion/dashboard/dashboard-item/dashboard-item.component.scss
  src/app/onion/dashboard/dashboard-item/dashboard-item.component.ts
Labels: review

#608 Fix Sidebar First Name Bug
  package-lock.json
  package.json
  src/app/core/auth.service.ts
  src/app/shared/navbar/navbar.component.html
Labels: bite size, bug, review

#603 Capitalize First Letter of Outcome details
  src/app/cube/details/outcomes-detail-view/outcomes-detail-view.component.ts
Labels: review

#614 Add simple HTTP Interceptor
  package-lock.json
  package.json
  src/app/auth/auth.module.ts
  src/app/clark.module.ts
  src/app/core/core.module.ts
  src/app/core/interceptor/httpconfig.interceptor.ts
  src/app/cube/collections/collection.module.ts
  src/app/cube/core/cube-core.module.ts
  src/app/cube/cube.module.ts
  src/app/onion/learning-object-builder/components/content-upload/app/content-upload.module.ts
  src/app/onion/onion.module.ts
Labels: review

#615 Add User Stats
  package-lock.json
  package.json
  src/app/cube/home/home.component.ts
  src/app/cube/home/stat-counters/stat-counters.component.html
  src/app/cube/usage-stats/usage-stats.component.ts
Labels: review

#617 Remove usage of released flag
  package-lock.json
  package.json
  src/app/cube/browse/browse.component.ts
  src/app/cube/home/home.component.ts
  src/app/cube/shared/featured/featured.component.ts
  src/app/shared/interfaces/query.ts
Labels: review

#610 Remove meatball if reviewing and add tooltip
  package-lock.json
  package.json
  src/app/onion/dashboard/dashboard-item/dashboard-item.component.html
  src/app/onion/dashboard/dashboard-item/dashboard-item.component.scss
Labels: review

#623 Modify the user-information component to use new profile route
  package-lock.json
  package.json
  src/app/cube/learning-object.service.ts
  src/app/cube/user-profile/user-information/user-information.component.ts
  src/environments/route.ts
Labels: review

#625 Fix bug where an error thrown from the message component isn't being caught
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/components/column-wrapper/column-wrapper.component.ts
Labels: review

#628 Fix bug where potentially null string values are being trimmed
  package-lock.json
  package.json
  src/app/cube/home/home.component.ts
Labels: review

#629 Fix bug where closing the filter menu on dashboard triggers an error
  package-lock.json
  package.json
  src/app/onion/dashboard/dashboard.component.ts
Labels: review

#631 Fix bug where closing the submission menu in the builder throws an error
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.ts
Labels: review

#637 Request saves and downloads from library service
  package-lock.json
  package.json
  src/app/cube/core/usage-stats/usage-stats.service.ts
  src/environments/route.ts
Labels: review

#636 Implement minor dashboard style enhancements
  package-lock.json
  package.json
  src/app/onion/dashboard/dashboard.component.html
  src/app/onion/dashboard/dashboard.component.scss
  src/app/onion/dashboard/dashboard.component.ts
Labels: enhancement, review

#635 Fix bug where column height for builder isn't calculated if message service returns a malformed response
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/components/column-wrapper/column-wrapper.component.ts
Labels: bug, review

#619 Update review stat to accurately reflect objects under review
  package-lock.json
  package.json
  src/app/cube/home/home.component.ts
  src/app/cube/shared/types/learning-object-stats.ts
Labels: review

#639 Modify usage-stats page to display correct number of review objects
  package-lock.json
  package.json
  src/app/cube/usage-stats/usage-stats.component.ts
Labels: bite size, bug, review

#640 Hide unreleased children on details page
  package-lock.json
  package.json
  src/app/cube/details/details.component.html
  src/app/cube/details/details.component.ts
Labels: bug, review

#646 Fix bad refresh token request
  package-lock.json
  package.json
  src/app/auth/email-verified/email-verified.component.html
  src/app/auth/email-verified/email-verified.component.ts
Labels: bug, review

#649 Fix bug where users with privileged access can't download learning objects
  package-lock.json
  package.json
  src/app/core/auth.service.ts
Labels: review

#650 Add Library Stats Request back into Client
  package-lock.json
  package.json
  src/app/cube/core/usage-stats/usage-stats.service.ts
  src/environments/route.ts
Labels: enhancement, review

#659 Hide navbar on email verification page
  package-lock.json
  package.json
  src/app/auth/email-verified/email-verified.component.ts
Labels: review

#658 Update learning object cards/list-items to display the full list of contributors instead of just the author
  package-lock.json
  package.json
  src/app/shared/learning-object/learning-object.component.html
  src/app/shared/learning-object/learning-object.component.scss
  src/app/shared/learning-object/learning-object.component.ts
Labels: enhancement, review

#674 Email verification tests
  .circleci/config.yml
  jest.config.js
  karma.conf.js
  package-lock.json
  package.json
  src/app/auth/email-verified/email-verified.component.spec.ts
  src/jestGlobalMocks.ts
  src/setup-jest.ts
  src/test.js
Labels: review

#675 Fix failing tests
  .circleci/config.yml
  src/app/auth/auth.component.spec.ts
  src/app/auth/forgot-password/forgot-password.component.spec.ts
  src/app/auth/forgot-password/forgot-password.component.ts
  src/app/auth/login/login.component.spec.ts
  src/app/auth/reset-password/reset-password.component.spec.ts
  src/jestGlobalMocks.ts
Labels: review

#651 Feature/response ui
  package-lock.json
  package.json
  src/app/core/rating.service.ts
  src/app/cube/details/details.component.html
  src/app/cube/details/details.component.ts
  src/app/shared/learning-object-ratings/learning-object-ratings.component.html
  src/app/shared/learning-object-ratings/learning-object-ratings.component.scss
  src/app/shared/learning-object-ratings/learning-object-ratings.component.ts
  src/app/shared/new-rating-response/new-rating-response.component.html
  src/app/shared/new-rating-response/new-rating-response.component.scss
  src/app/shared/new-rating-response/new-rating-response.component.ts
  src/app/shared/new-rating/new-rating.component.html
  src/app/shared/new-rating/new-rating.component.ts
  src/app/shared/shared.module.ts
  src/environments/route.ts
Labels: review

#678 Handle observable errors
  package-lock.json
  package.json
  src/app/core/auth.service.ts
  src/app/core/cartv2.service.ts
  src/app/core/collection.service.ts
  src/app/core/messages.service.ts
  src/app/core/outcome.service.ts
  src/app/core/rating.service.ts
  src/app/core/user.service.ts
  src/app/cube/core/usage-stats/usage-stats.service.ts
  src/app/cube/learning-object.service.ts
  src/app/onion/core/learning-object.service.ts
  src/app/onion/core/suggestion.service.ts
  src/app/onion/learning-object-builder/components/content-upload/app/services/file-storage.service.ts
Labels: review

#681 Hide revise button if Learning Object is released
  package-lock.json
  package.json
  src/app/cube/details/action-panel/action-panel.component.ts
Labels: review

#673 Search for Learning Objects in the Curator Dashboard (Unit 1 of 2)
  src/app/admin/admin.module.ts
  src/app/admin/components/search-bar/search-bar.component.html
  src/app/admin/components/search-bar/search-bar.component.scss
  src/app/admin/components/search-bar/search-bar.component.spec.ts
  src/app/admin/components/search-bar/search-bar.component.ts
  src/app/admin/pages/learning-objects/learning-objects.component.html
  src/app/admin/pages/learning-objects/learning-objects.component.scss
  src/app/admin/pages/learning-objects/learning-objects.component.ts
  src/app/onion/onion.module.ts
  src/app/shared/dashboard-item/dashboard-item.component.html
  src/app/shared/dashboard-item/dashboard-item.component.scss
  src/app/shared/dashboard-item/dashboard-item.component.spec.ts
  src/app/shared/dashboard-item/dashboard-item.component.ts
  src/app/shared/shared.module.ts
Labels: review

#680 Allow Admins/Editors to edit Learning Object in Builder
  package-lock.json
  package.json
  src/app/clark.routing.ts
  src/app/core/access-group-guard.ts
  src/app/core/auth.service.ts
  src/app/core/core.module.ts
  src/app/cube/details/action-panel/action-panel.component.html
  src/app/cube/details/action-panel/action-panel.component.ts
  src/app/onion/core/learning-object.service.ts
  src/app/onion/dashboard/dashboard.component.ts
  src/app/onion/learning-object-builder/builder-store.service.ts
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.html
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.scss
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.ts
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.html
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.ts
  src/app/onion/learning-object-builder/learning-object-builder.component.html
  src/app/onion/learning-object-builder/learning-object-builder.component.ts
Labels: review

#685 Revert Hide revise button if Learning Object is released
  package-lock.json
  package.json
  src/app/cube/details/action-panel/action-panel.component.ts
Labels: review
