Repository Cyber4All/clark-client, pull requests merged in 2019-04, with the labels that each got.

#771 Fix Editors being kicked from builder
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/learning-object-builder.component.ts
Labels: review

#773 Replace ToS with Correct Version
  package-lock.json
  package.json
  src/assets/Terms.pdf
Labels: review

#772 Add organization to learning object cards and implement minor UI improvements
  package-lock.json
  package.json
  src/app/cube/details/details.component.html
  src/app/cube/user-profile/user-information/user-information.component.html
  src/app/shared/learning-object/learning-object.component.html
  src/app/shared/learning-object/learning-object.component.ts
Labels: review

#767 General builder UI and logic clean up
  package-lock.json
  package.json
  src/app/onion/core/learning-object.service.ts
  src/app/onion/learning-object-builder/builder-store.service.ts
  src/app/onion/learning-object-builder/components/column-wrapper/column-wrapper.component.html
  src/app/onion/learning-object-builder/components/column-wrapper/column-wrapper.component.scss
  src/app/onion/learning-object-builder/components/scaffold/scaffold.component.html
  src/app/onion/learning-object-builder/components/scaffold/scaffold.component.ts
  src/app/onion/learning-object-builder/learning-object-builder.component.html
Labels: review

#776 Remove Clark logo from footer
  package-lock.json
  package.json
  src/app/cube/shared/footer/footer.component.html
  src/app/cube/shared/footer/footer.component.scss
Labels: review

#760 Allow admins to add curators and reviewers to collections
  cypress.json
  cypress/fixtures/route.json
  cypress/integration/Collection Dashboard/admin-privileges.spec.js
  cypress/support/commands.js
  package.json
  src/_vars.scss
  src/app/admin/admin.module.ts
  src/app/admin/components/filter-search/filter-search.component.ts
  src/app/admin/components/user-card/user-card.component.html
  src/app/admin/components/user-card/user-card.component.scss
  src/app/admin/components/user-card/user-card.component.ts
  src/app/admin/components/user-privileges/privileges-list/privileges-list.component.html
  src/app/admin/components/user-privileges/privileges-list/privileges-list.component.scss
  src/app/admin/components/user-privileges/privileges-list/privileges-list.component.spec.ts
  src/app/admin/components/user-privileges/privileges-list/privileges-list.component.ts
  src/app/admin/components/user-privileges/user-privileges.component.html
  src/app/admin/components/user-privileges/user-privileges.component.scss
  src/app/admin/components/user-privileges/user-privileges.component.spec.ts
  src/app/admin/components/user-privileges/user-privileges.component.ts
  src/app/admin/pages/learning-objects/learning-objects.component.ts
  src/app/admin/pages/users/users.component.html
  src/app/admin/pages/users/users.component.scss
  src/app/admin/pages/users/users.component.ts
  src/app/core/core.module.ts
  src/app/core/privilege.service.ts
  src/app/core/user.service.ts
  src/app/cube/details/action-panel/action-panel.component.html
  src/app/onion/dashboard/dashboard.component.html
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.html
  src/app/shared/carousel/carousel.animation.ts
  src/app/shared/carousel/carousel.component.html
  src/app/shared/carousel/carousel.component.scss
  src/app/shared/carousel/carousel.component.spec.ts
  src/app/shared/carousel/carousel.component.ts
  src/app/shared/collections-grid/collections-grid.component.html
  src/app/shared/collections-grid/collections-grid.component.scss
  src/app/shared/collections-grid/collections-grid.component.spec.ts
  src/app/shared/collections-grid/collections-grid.component.ts
  src/app/shared/learning-object/learning-object.component.html
  src/app/shared/popup-templates/collection-selector-popup/collection-selector-popup.component.html
  src/app/shared/popup-templates/collection-selector-popup/collection-selector-popup.component.scss
  src/app/shared/popup-templates/collection-selector-popup/collection-selector-popup.component.ts
  src/app/shared/popup-templates/download-notice-popup/download-notice-popup.component.html
  src/app/shared/popup-templates/download-notice-popup/download-notice-popup.component.scss
  src/app/shared/popup-templates/download-notice-popup/download-notice-popup.component.ts
  src/app/shared/popups/popup.module.ts
  src/app/shared/shared.module.ts
  src/environments/route.ts
  src/environments/status-descriptions.ts
Labels: review

#763 Redirect to dash from builder if editing released object
  package-lock.json
  package.json
  src/app/onion/core/core.module.ts
  src/app/onion/core/learning-object-builder.guard.ts
  src/app/onion/dashboard/dashboard.component.ts
  src/app/onion/learning-object-builder/learning-object-builder.component.ts
  src/app/onion/onion.routing.ts
Labels: review

#778 Direct privileged users uploads to new file upload service
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/components/content-upload/app/services/file-storage.service.ts
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/environments/route.ts
Labels: review

#777 Tests for feature/#572
  cypress/fixtures/creds.json
  cypress/integration/browse.spec.js
  cypress/integration/dashboard.spec.js
  cypress/integration/details.spec.js
  cypress/integration/home.spec.js
  cypress/integration/library.spec.js
  cypress/integration/user.spec.js
  cypress/support/commands.js
Labels: review

#774 Add featured collections page
  package-lock.json
  package.json
  src/app/cube/collection-details/collection-details.component.html
  src/app/cube/collection-details/collection-details.component.scss
  src/app/cube/collection-details/collection-details.component.ts
  src/app/cube/collection-details/collection-details.module.ts
  src/app/cube/collections/collection.component.html
  src/app/cube/collections/collections.component.html
  src/app/cube/collections/collections.component.scss
  src/app/cube/collections/collections.component.spec.ts
  src/app/cube/collections/collections.component.ts
  src/app/cube/cube.module.ts
  src/app/cube/cube.routing.ts
  src/app/cube/home/components/collections/collections.component.html
  src/app/cube/home/components/collections/collections.component.scss
  src/app/cube/shared/featured/featured.component.html
  src/app/cube/shared/featured/featured.component.scss
  src/app/shared/collection-card/collection-card.component.html
  src/app/shared/collection-card/collection-card.component.scss
  src/app/shared/collection-card/collection-card.component.spec.ts
  src/app/shared/collection-card/collection-card.component.ts
  src/app/shared/shared.module.ts
Labels: review

#709 Curators should be able to add/remove reviewers inside their collections
  cypress/fixtures/route.json
  cypress/integration/browse.spec.js
  cypress/integration/collection_dashboard.spec.js
  cypress/integration/dashboard.spec.js
  cypress/integration/details.spec.js
  cypress/integration/home.spec.js
  cypress/integration/library.spec.js
  cypress/integration/register.spec.js
  cypress/integration/user.spec.js
  cypress/support/commands.js
  package.json
  src/app/admin/admin.module.ts
  src/app/admin/components/sidebar/sidebar.component.html
  src/app/admin/components/user-card/user-card.component.html
  src/app/admin/components/user-card/user-card.component.ts
  src/app/admin/components/user-search-wrapper/user-search-wrapper.component.html
  src/app/admin/components/user-search-wrapper/user-search-wrapper.component.scss
  src/app/admin/components/user-search-wrapper/user-search-wrapper.component.spec.ts
  src/app/admin/components/user-search-wrapper/user-search-wrapper.component.ts
  src/app/admin/pages/learning-objects/learning-objects.component.html
  src/app/admin/pages/learning-objects/learning-objects.component.ts
  src/app/admin/pages/users/users.component.html
  src/app/admin/pages/users/users.component.scss
  src/app/admin/pages/users/users.component.ts
  src/app/core/auth-guard.service.ts
  src/app/core/user.service.ts
  src/app/shared/navbar/navbar.component.html
  src/environments/route.ts
Labels: review, user story

#781 update existing change log route
  package-lock.json
  package.json
  src/app/core/changelog.service.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.ts
  src/environments/route.ts
Labels: review

#782 Implement pagination on learning objects page of collection dashboard
  src/app/admin/components/user-search-wrapper/user-search-wrapper.component.ts
  src/app/admin/pages/learning-objects/learning-objects.component.html
  src/app/admin/pages/learning-objects/learning-objects.component.scss
  src/app/admin/pages/learning-objects/learning-objects.component.ts
  src/app/admin/pages/users/users.component.ts
  src/app/core/user.service.ts
  src/app/onion/learning-object-builder/components/user-dropdown/user-dropdown.component.ts
  src/app/shared/dashboard-item/dashboard-item.component.ts
  src/app/shared/interfaces/query.ts
  src/environments/route.ts
Labels: review

#783 Fix bug where capital letters in emails are considered invalid in the registration page
  package-lock.json
  package.json
  src/app/auth/register/register.component.ts
Labels: review

#784 Implement client-side performance enhancements
  .circleci/config.yml
  package-lock.json
  package.json
  src/app/cube/home/components/splash/splash.component.ts
  src/app/onion/learning-object-builder/components/content-upload/app/content-upload.module.ts
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.html
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.ts
  src/app/onion/learning-object-builder/components/content-upload/environments/environment.ts
  src/app/onion/learning-object-builder/components/scaffold/hierarchy/hierarchy.component.html
  src/app/onion/onion.routing.ts
  src/assets/images/lecturer.jpg
  src/assets/images/servers.jpg
  src/entity/learning-object/learning-object.ts
Labels: review

#723 Add toggle to switch between released and revised versions of a learning object
  cypress/fixtures/creds.json
  cypress/integration/browse.spec.js
  cypress/integration/dashboard.spec.js
  cypress/integration/details.spec.js
  cypress/integration/home.spec.js
  cypress/integration/library.spec.js
  cypress/integration/user.spec.js
  cypress/support/commands.js
  package-lock.json
  package.json
  src/app/core/cartv2.service.ts
  src/app/cube/cart/cart.component.ts
  src/app/cube/details/action-panel/action-panel.component.html
  src/app/cube/details/action-panel/action-panel.component.ts
  src/app/cube/details/details.component.html
  src/app/cube/details/details.component.scss
  src/app/cube/details/details.component.ts
  src/app/cube/details/details.module.ts
  src/app/cube/details/reviewer-panel/reviewer-panel.component.html
  src/app/cube/details/reviewer-panel/reviewer-panel.component.scss
  src/app/cube/details/reviewer-panel/reviewer-panel.component.spec.ts
  src/app/cube/details/reviewer-panel/reviewer-panel.component.ts
  src/app/cube/details/version-switch/version-switch.component.html
  src/app/cube/details/version-switch/version-switch.component.scss
  src/app/cube/details/version-switch/version-switch.component.spec.ts
  src/app/cube/details/version-switch/version-switch.component.ts
  src/app/cube/learning-object.service.ts
  src/app/shared/learning-object/learning-object.component.ts
  src/environments/route.ts
Labels: review

#790 Fix rating UI tries to edit a deleted rating
  package-lock.json
  package.json
  src/app/core/rating.service.ts
  src/app/cube/details/details.component.ts
Labels: review

#785 Update learning object submission routes
  package-lock.json
  package.json
  src/app/core/collection.service.ts
  src/app/onion/core/learning-object.service.ts
  src/app/onion/dashboard/dashboard.component.ts
  src/app/onion/learning-object-builder/builder-store.service.ts
  src/environments/route.ts
Labels: review

#789 Fix bug where children section of details page isn't displaying due to querying on old component properties
  package-lock.json
  package.json
  src/app/cube/details/details.component.html
  src/app/cube/details/details.component.ts
Labels: review

#787 Add generic logos to collection submission selector
  package-lock.json
  package.json
  src/app/shared/popups/templates/collection-selector/collection-selector.component.html
  src/app/shared/popups/templates/collection-selector/collection-selector.component.scss
Labels: bite size, bug, review

#792 Compress homepage image and leaves background image on auth
  package-lock.json
  package.json
  src/assets/images/background_mask_compressed.png
  src/assets/images/lecturer.jpg
Labels: review

#788 Remove Acronym from login screen
  package-lock.json
  package.json
  src/app/auth/email-verified/email-verified.component.html
  src/app/auth/forgot-password/forgot-password.component.html
  src/app/auth/login/login.component.html
  src/app/auth/register/register.component.html
  src/app/auth/reset-password/reset-password.component.html
Labels: review

#793 Change homepage splash image
  package-lock.json
  package.json
  src/app/cube/home/components/splash/splash.component.scss
  src/assets/images/blair.jpg
  src/assets/images/lecturer.jpg
Labels: review

#795 Fix multipart upload from folder structure
  package-lock.json
  package.json
  src/app/onion/learning-object-builder/components/content-upload/app/upload/upload.component.ts
Labels: review

#796 Security patches
  package-lock.json
  package.json
Labels: review

#797 Prevent users from downloading learning objects without a verified email
  package-lock.json
  package.json
  src/app/auth/register/personal-info/personal-info.component.ts
  src/app/auth/register/profile-info/profile-info.component.ts
  src/app/clark.component.ts
  src/app/core/auth.service.ts
  src/app/core/user.service.ts
  src/app/cube/details/action-panel/action-panel.component.html
  src/app/cube/details/action-panel/action-panel.component.scss
  src/app/cube/details/action-panel/action-panel.component.ts
  src/app/cube/details/details.component.html
  src/app/cube/details/details.component.scss
  src/app/cube/details/details.component.ts
  src/app/shared/email-banner/email-banner.component.ts
Labels: review

#794 Implement toast notification for conveying error messages
  src/app/admin/admin.component.ts
  src/app/admin/components/filter-search/filter-search.component.ts
  src/app/admin/components/user-privileges/user-privileges.component.ts
  src/app/admin/components/user-search-wrapper/user-search-wrapper.component.ts
  src/app/admin/pages/learning-objects/learning-objects.component.ts
  src/app/admin/pages/users/users.component.ts
Labels: review

#800 Remove No Description Here!
  package-lock.json
  package.json
  src/app/shared/filesystem/file-list-view/file-list-view.component.html
Labels: review

#801 Add View All back to Collections
  package-lock.json
  package.json
  src/app/cube/collection-details/collection-details.component.html
  src/app/cube/collection-details/collection-details.component.scss
  src/app/cube/collection-details/collection-details.component.ts
  src/app/cube/collections/collections.component.html
  src/app/cube/shared/featured/featured.component.html
  src/app/cube/shared/featured/featured.component.scss
  src/app/cube/shared/featured/featured.component.ts
  src/app/cube/shared/featured/featured.copy.ts
Labels: review

#786 Story/author change logs
  package-lock.json
  package.json
  src/app/onion/core/learning-object.service.ts
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.html
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.scss
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.html
  src/app/onion/learning-object-builder/components/editor-action-panel/edit-changelog/edit-changelog.component.html
  src/app/onion/learning-object-builder/components/editor-action-panel/edit-changelog/edit-changelog.component.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.module.ts
  src/environments/route.ts
Labels: review

#802 Increase performance of the users page in collection dashboard
  package-lock.json
  src/app/admin/admin.component.html
  src/app/admin/admin.component.scss
  src/app/admin/admin.component.ts
  src/app/admin/admin.module.ts
  src/app/admin/admin.routing.ts
  src/app/admin/components/sidebar/sidebar.component.html
  src/app/admin/components/user-card/user-card.component.html
  src/app/admin/components/user-card/user-card.component.scss
  src/app/admin/components/user-card/user-card.component.ts
  src/app/admin/pages/users/users.component.html
  src/app/admin/pages/users/users.component.ts
  src/app/core/user.service.ts
  src/app/shared/learning-object/learning-object.component.ts
  src/app/shared/shared.module.ts
Labels: review

#804 Revert "Story/author change logs"
  package-lock.json
  package.json
  src/app/onion/core/learning-object.service.ts
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.html
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.scss
  src/app/onion/learning-object-builder/components/builder-navbar/builder-navbar.component.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/change-status-modal/change-status-modal.component.html
  src/app/onion/learning-object-builder/components/editor-action-panel/edit-changelog/edit-changelog.component.html
  src/app/onion/learning-object-builder/components/editor-action-panel/edit-changelog/edit-changelog.component.ts
  src/app/onion/learning-object-builder/components/editor-action-panel/editor-action-panel.module.ts
  src/environments/route.ts
Labels: review

#809 Revert the change to the homepage splash image and tweak the size of the collection cards
  package-lock.json
  package.json
  src/app/cube/home/components/splash/splash.component.scss
  src/app/shared/collection-card/collection-card.component.scss
  src/assets/images/blair.jpg
  src/assets/images/lecturer.jpg
Labels: review
