Repository Cyber4All/clark-client, pull requests merged in 2019-10, with the labels that each got.

#969 Update rating service queries for revision
  package-lock.json
  package.json
  src/app/core/rating.service.ts
  src/app/cube/old-details/details.component.ts
  src/app/onion/dashboard/components/side-panel-content/side-panel-content.component.ts
  src/entity/learning-object/learning-object.ts
  src/environments/route.ts
Labels: review

#985 Import uri retriever service and use children retriever
  package-lock.json
  package.json
  src/app/core/uri-retriever.service.ts
  src/app/onion/core/learning-object.service.ts
  src/app/onion/dashboard/components/dashboard-item/dashboard-item.component.html
  src/app/onion/dashboard/components/dashboard-item/dashboard-item.component.ts
  src/app/onion/dashboard/components/side-panel-content/revision/revision.component.ts
  src/app/onion/dashboard/dashboard.component.ts
  src/app/onion/learning-object-builder/builder-store.service.ts
Labels: bite size, bug

#988 Hotfix/mobile filters scroll
  package-lock.json
  package.json
  src/app/cube/browse/browse.component.scss
Labels: bite size, bug

#991 Add scrolling to the pie and map chart
  package-lock.json
  package.json
  src/app/cube/usage-stats/heat-map/heat-map.component.scss
Labels: WIP, bite size, bug
